name: Build and deploy node site to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        continue-on-error: true
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        uses: actions/setup-node@v2
      - run:  |
          cd ${{ github.workspace }}
          npm install
          npm run build


           
      - name: Move 
        run: |
          cd ${{ github.workspace }}
          mv dist/assets/index.html dist/ 
          rm -rf node_modules
          
      
      - name: Invoke Deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
        uses: JamesIves/github-pages-deploy-action@4.1.4
